// porkxi-astro/src/components/TarjetasKpi.vue
<template>
  <div class="tarjetas-kpi">
    <div class="tarjeta-kpi tarjeta-kpi--colombia">
      <div class="tarjeta-kpi__etiqueta">🇨🇴 Último dato Colombia</div>
      <div class="tarjeta-kpi__valor">2024</div>
      <div class="tarjeta-kpi__descripcion">10,668,276 cabezas · Fuente: Porcinews</div>
    </div>
    <div class="tarjeta-kpi tarjeta-kpi--usa">
      <div class="tarjeta-kpi__etiqueta">🇺🇸 Último dato EE.UU.</div>
      <div class="tarjeta-kpi__valor">Dic 2025</div>
      <div class="tarjeta-kpi__descripcion">75,500,000 cabezas · Fuente: USDA NASS</div>
    </div>
    <div class="tarjeta-kpi tarjeta-kpi--alerta">
      <div class="tarjeta-kpi__etiqueta">📅 Frecuencia de reporte</div>
      <div class="tarjeta-kpi__valor">Anual vs Trimestral</div>
      <div class="tarjeta-kpi__descripcion">COL: 1 dato/año · USA: 4 datos/año</div>
    </div>
    <div class="tarjeta-kpi tarjeta-kpi--cerdo">
      <div class="tarjeta-kpi__etiqueta">Escala comparativa</div>
      <div class="tarjeta-kpi__valor">7.1x</div>
      <div class="tarjeta-kpi__descripcion">EE.UU. tiene 7.1 veces más cerdos que Colombia</div>
    </div>
  </div>
</template>

<script setup>
</script>

<style scoped>
</style>

// src/componentes/TarjetasKpi.jsx
import TarjetaKpi from './TarjetaKpi';

function TarjetasKpi() {
  return (
    <div className="tarjetas-kpi">
      <TarjetaKpi 
        color="colombia"
        etiqueta="🇨🇴 Último dato Colombia"
        valor="2024"
        descripcion="10,668,276 cabezas · Fuente: Porcinews"
      />
      <TarjetaKpi 
        color="usa"
        etiqueta="🇺🇸 Último dato EE.UU."
        valor="Dic 2025"
        descripcion="75,500,000 cabezas · Fuente: USDA NASS"
      />
      <TarjetaKpi 
        color="alerta"
        etiqueta="📅 Frecuencia de reporte"
        valor="Anual vs Trimestral"
        descripcion="COL: 1 dato/año · USA: 4 datos/año"
      />
      <TarjetaKpi 
        color="cerdo"
        etiqueta="Escala comparativa"
        valor="7.1x"
        descripcion="EE.UU. tiene 7.1 veces más cerdos que Colombia"
      />
    </div>
  );
}

export default TarjetasKpi;
